- alias: "Media player paused/stopped"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      from: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: numeric_state
      entity_id: sensor.living_room_lux
      below: 5000
    - condition: state
      entity_id: group.all_devices
      state: 'home'
  action:
      service: scene.turn_on
      entity_id: scene.living_room_normal

- alias: "Media player playing"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      to: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: group.all_devices
      state: 'home'
  action:
      service: scene.turn_on
      entity_id: scene.living_room_dim



- alias: Turn on lights when anyone gets home
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'on'
    - platform: state
      entity_id: group.all_devices
      to: 'home'
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
    - condition: state
      entity_id: media_player.kodi
      state: 'idle'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_normal

- alias: Switch on lights when it get's darker 
  trigger:
  - platform: numeric_state
    entity_id: sensor.living_room_lux
    below: 6000
  - platform: time
    minutes: '/2'
    seconds: 0
  condition:
  - condition: numeric_state
    entity_id: sensor.living_room_lux
    below: 6000
  - condition: state
    entity_id: group.all_devices
    state: 'home'
  - condition: state
    entity_id: input_boolean.sleeping
    state: 'off'
  - condition: state
    entity_id: light.living_room
    state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.living_room 
      data:
        brightness: 125
        kelvin: 3500
        transition: 10

- alias: Increase lights when it get's darker 
  trigger:
  - platform: numeric_state
    entity_id: sensor.living_room_lux
    below: 6000
  - platform: time
    minutes: '/2'
    seconds: 0
  condition:
  - condition: numeric_state
    entity_id: sensor.living_room_lux
    below: 6000
  - condition: state
    entity_id: group.all_devices
    state: 'home'
  - condition: state
    entity_id: input_boolean.sleeping
    state: 'off'
  - condition: numeric_state
    entity_id: light.living_room
    value_template: '{{ states.light.living_room.attributes.brightness }}'
    below: 245
  - condition: state
    entity_id: media_player.kodi
    state: 'idle'
  action:
    - service: light.turn_on
      entity_id: light.living_room 
      data_template:
        brightness: '{{states.light.living_room.attributes.brightness + 10}}'
        transition: 60

- alias: Decrease lights when it get's lighter 
  trigger:
  - platform: numeric_state
    entity_id: sensor.living_room_lux
    above: 7000
  - platform: time
    minutes: '/2'
    seconds: 0
  condition:
  - condition: numeric_state
    entity_id: sensor.living_room_lux
    above: 7000
  - condition: state
    entity_id: group.all_devices
    state: 'home'
  - condition: state
    entity_id: input_boolean.sleeping
    state: 'off'
  - condition: numeric_state
    entity_id: light.living_room
    value_template: '{{ states.light.living_room.attributes.brightness }}'
    above: 10
  action:
    - service: light.turn_on
      entity_id: light.living_room 
      data_template:
        brightness: '{{states.light.living_room.attributes.brightness - 10}}'
        transition: 60

- alias: Stops lights when it get's lighter 
  trigger:
  - platform: numeric_state
    entity_id: sensor.living_room_lux
    above: 7000
  - platform: time
    minutes: '/2'
    seconds: 0
  condition:
  - condition: numeric_state
    entity_id: sensor.living_room_lux
    above: 7000
  - condition: state
    entity_id: group.all_devices
    state: 'home'
  - condition: state
    entity_id: input_boolean.sleeping
    state: 'off'
  - condition: numeric_state
    entity_id: light.living_room
    value_template: '{{ states.light.living_room.attributes.brightness }}'
    below: 10
  action:
    - service: light.turn_off
      entity_id: light.living_room 
      data:
        transition: 60




- alias: Morning lighting workday
  trigger:
    - platform: time
      at: '06:30:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'on'
  action:
    - service: light.turn_on 
      entity_id: light.bedroom 
      data:
        brightness: 1
        kelvin: 2200
    - delay: 00:00:10
    - service: light.turn_on 
      entity_id: light.bedroom 
      data:
        brightness: 125
        kelvin: 2200
        transition: 900
    - delay: 00:15:00 
    - service: light.turn_on 
      entity_id: light.bedroom 
      data:
        brightness: 255
        kelvin: 6500
        transition: 900

- alias: Morning lighting weekend
  trigger:
    - platform: time
      at: '09:30:00'
  condition:
    - condition: time
      weekday:
        - fri
        - sat
        - sun
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'on'
  action:
    - service: light.turn_on 
      entity_id: light.bedroom 
      data:
        brightness: 1
        kelvin: 2200
    - delay: 00:00:10
    - service: light.turn_on 
      entity_id: light.bedroom 
      data:
        brightness: 125
        kelvin: 2200
        transition: 900
    - delay: 00:15:00 
    - service: light.turn_on 
      entity_id: light.bedroom 
      data:
        brightness: 255
        kelvin: 6500
        transition: 900

- alias: Sleep time
  trigger:
    - platform: state
      entity_id: input_boolean.sleeping
      to: 'on'
  action:
    - service: media_player.media_stop
      entity_id: media_player.kodi
    - service: light.turn_on 
      entity_id: light.bedroom 
      data:
        brightness: 125
        kelvin: 2200
        transition: 10
    - service: light.turn_on 
      entity_id: light.living_room 
      data:
        brightness: 125
        kelvin: 2200
        transition: 30
    - delay: 00:05:00
    - service: light.turn_off 
      entity_id: light.living_room 
      data:
        transition: 300
    - delay: 00:10:00
    - service: light.turn_off 
      entity_id: light.bedroom 
      data:
        transition: 300

- alias: Woke up time
  trigger:
    - platform: state
      entity_id: input_boolean.sleeping
      to: 'off'
  action:
    - service: light.turn_on 
      entity_id: light.bedroom 
      data:
        brightness: 125
        kelvin: 3500
        transition: 60
    - service: light.turn_on 
      entity_id: light.living_room 
      data:
        brightness: 125
        kelvin: 3500
    - delay: 00:01:00
    - service: light.turn_off 
      entity_id: light.bedroom 
      data:
        transition: 60
    - service: light.turn_on 
      entity_id: light.living_room 
      data_template:
        brightness: '{{states.light.living_room.attributes.brightness}}'
        kelvin: 6500
        transition: 900
    - delay: 00:15:00
    - service: light.turn_on 
      entity_id: light.living_room 
      data_template:
        brightness: '{{states.light.living_room.attributes.brightness}}'
        kelvin: 4000
        transition: 15

- alias: "Presence detected during night, light red lights"
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'on'
      from: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'on'
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    - condition: time
      after: '01:00:00'
      before: '06:50:00'
  action:
    - service: light.turn_on 
      entity_id: light.living_room 
      data:
        brightness: 125
        color_name: 'red'
        transition: 5
    - delay: 00:05:00
    - service: light.turn_off 
      entity_id: light.living_room 
      data:
        transition: 300

- alias: "Presence detected at woke up"
  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion
      to: 'on'
      from: 'off'
  condition:
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'on'
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    - condition: time
      after: '06:50:00'
      before: '15:00:00'
  action:
    - service: input_boolean.turn_off 
      entity_id: input_boolean.sleeping



- alias: Bed time
  trigger:
    - platform: time
      at: '22:45:00'
  condition:
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
    - condition: state
      entity_id: group.all_devices
      state: 'home'
  action:
    - service: light.turn_on 
      entity_id: light.living_room 
      data:
        flash: short
    - delay: 00:00:10
    - service: light.turn_on 
      entity_id: light.living_room 
      data:
        brightness: 125
        kelvin: 2200
        transition: 900
    - delay: 00:15:00
    - service: light.turn_on 
      entity_id: light.living_room 
      data:
        flash: short


- alias: Away
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'not_home'
      from: 'home'
  action:
    - service: media_player.media_stop
      entity_id: media_player.kodi
    - service: light.turn_off
      entity_id: group.all_lights
    - service: notify.html5_nexus5
      data:
        title: "Plus personne n'est a la maison"
        message: "... j'ai tout eteint."


- alias: Shower time
  trigger:
    - platform: time
      at: '08:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
    - condition: state
      entity_id: group.all_devices
      state: 'home'
  action:
    - service: light.turn_on 
      entity_id: light.living_room 
      data:
        flash: short

- alias: Leave time
  trigger:
    - platform: time
      at: '08:35:00'
  condition:
    - condition: state
      entity_id: input_boolean.sleeping
      state: 'off'
    - condition: state
      entity_id: group.all_devices
      state: 'home'
  action:
    - service: light.turn_on 
      entity_id: light.living_room 
      data:
        flash: short
