# https://github.com/happyleavesaoc/my-home-automation/tree/master/homeassistant/packages
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone 
  #customize: !include customize.yaml
  packages: !include_dir_named packages



automation: !include_dir_merge_list automations
camera: !include_dir_merge_list cameras
binary_sensor: !include_dir_merge_list binary_sensors
device_tracker: !include_dir_merge_list device_trackers
group: !include_dir_merge_named groups
input_boolean: !include_dir_merge_named input_booleans
intent_script: !include_dir_merge_named intent_scripts
light: !include_dir_merge_list lights
notify: !include_dir_merge_list notifications
media_player: !include_dir_merge_list media_players
scene: !include_dir_merge_list scenes
sensor: !include_dir_merge_list sensors
switch: !include_dir_merge_list switches
script: !include_dir_merge_named scripts

logger: !include logger.yaml
logbook: !include logbook.yaml
tts: !include tts.yaml



sun:
frontend:
history:
config:

wake_on_lan:
snips:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret api_password 
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url



# TODO: google calendar
  # - morning briefing on event
# TODO: moring briefing on rain
# TODO: previous day briefing on event if not at home 
# TODO: tea timer (+ snips)
# TODO: turn off kitchen when kodi plays
