- platform: rest
  resource: !secret hue_lux_living_room
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Living Room Lux'
          
- platform: rest
  resource: !secret hue_temperature_living_room
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Living Room Temperature'
