- alias: "Media player paused"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      to: 'paused'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: numeric_state
      entity_id: sensor.living_room_lux
      below: 6000
    - condition: state
      entity_id: group.all_devices
      state: 'home'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_normal
    - service: scene.turn_on
      entity_id: scene.kitchen_on



- alias: "Media player stopped"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      from: 'playing'
      to: 'idle'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: group.all_devices
      state: 'home'
  action:
    - service: scene.turn_on
      entity_id: scene.kitchen_off





- alias: "Media player playing"
  trigger:
    - platform: state
      entity_id: media_player.kodi
      to: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: group.all_devices
      state: 'home'
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_dim
    - service: scene.turn_on
      entity_id: scene.kitchen_off

