homeassistant:
  customize:
    sensor.hass_version:
      friendly_name: Home Assitant
      icon: mdi:home-assistant
    sensor.rpi_hass_docker_image:
      friendly_name: rPI HASS docker image
      icon: mdi:home-assistant
    sensor.snips_docker_image:
      friendly_name: Snips docker image
      icon: mdi:ear-hearing

group:
        Software Version:
                - sensor.hass_version
                - sensor.rpi_hass_docker_image
                - sensor.snips_docker_image

sensor:
  - platform: scrape
    name: hass_version
    resource: https://home-assistant.io
    select: ".current-version h1"
    value_template: '{{ value.split(":")[1] }}'

  - platform: rest
    name: rpi_hass_docker_image
    resource: https://registry.hub.docker.com/v1/repositories/lroguet/rpi-home-assistant/tags
    value_template: '{{value_json[-1].name}}'
    
  - platform: rest
    name: snips_docker_image
    resource: https://registry.hub.docker.com/v1/repositories/snipsdocker/platform/tags
    value_template: '{{value_json[-2].name.split("-")[1]}}'
