homeassistant:
  customize:
    sun.sun:
      icon: mdi:weather-sunny
    
    
    sensor.dark_sky_humidity:
      icon: mdi:water-percent
      friendly_name: Humidity
    sensor.dark_sky_temperature:
      icon: mdi:thermometer
      friendly_name: Temperature
    sensor.dark_sky_summary:
      icon: mdi:leaf
      friendly_name: Conditions
    sensor.dark_sky_cloud_coverage:
      friendly_name: Cloud Coverage
    sensor.dark_sky_wind_speed:
      friendly_name: Wind Speed
    sensor.dark_sky_daily_high_temperature:
      hidden: true
    sensor.dark_sky_daily_low_temperature:
      hidden: true
    sensor.dark_sky_daily_summary:
      hidden: true
    sensor.dark_sky_hourly_summary:
      hidden: true
    
    
    sensor.pollen:
      hidden: true
    
    sensor.pollen_level:
      icon: mdi:chart-bar

group:
        Outdoors:
                - sensor.dark_sky_summary
                - sun.sun
                - sensor.dark_sky_temperature
                - sensor.dark_sky_humidity
                - sensor.dark_sky_cloud_coverage
                - sensor.dark_sky_wind_speed
                  #                - sensor.air_quality
                - sensor.season
                  #                - sensor.pollen_level
                  #                - sensor.cold_flu_risk
                - camera.weather_radar

camera:
        - platform: generic
          still_image_url: !secret weather_map_endpoint
          name: Weather Radar
          content_type: 'image/gif'

sensor:
        - platform: season
          #          - platform: rest
          #            name: pollen
          #            resource: !secret pollen_url
          #            value_template: "{{value_json.Location.periods[1].Index}}"
          #            scan_interval: 21600
          #            headers:
          #                    Referer: "https://www.pollen.com"
          #          - platform: rest
          #            name: cold_flu
          #            resource: !secret cold_flu_url
          #            value_template: "{{value_json.Location.periods[0].Index}}"
          #            scan_interval: 21600
          #            headers:
          #                    Referer: "https://www.pollen.com"
          #- platform: template
          #  sensors:
          #          air_quality_numeric:
          #                  value_template: !secret air_quality_sensor_template
          #          air_quality:
          #                  friendly_name: 'Air Quality'
          #                  value_template: >
          #                          {% if states.sensor.air_quality_numeric.state|int <= 50 %}
          #                          Good
          #                          {% elif states.sensor.air_quality_numeric.state|int <= 100 %}
          #                          Moderate
          #                          {% elif states.sensor.air_quality_numeric.state|int <= 150 %}
          #                          Unhealthy
          #                          {% endif %}
          #          pollen_level:
          #                  friendly_name: 'Pollen Level'
          #                  value_template: >-
          #                          {%- if states.sensor.pollen.state|float <= 2.4 %}
          #                          Low
          #                          {%- elif states.sensor.pollen.state|float <= 4.8 %}
          #                          Medium-Low
          #                          {%- elif states.sensor.pollen.state|float <= 7.2 %}
          #                          Medium
          #                          {%- elif states.sensor.pollen.state|float <= 9.6 %}
          #                          Medium-High
          #                          {%- elif states.sensor.pollen.state|float <= 12.0 %}
          #                          High
          #                          {% else %}
          #                          Unknown
          #                          {%- endif %}
          #          cold_flu_risk:
          #                  friendly_name: 'Cold & Flu Risk'
          #                  value_template: >-
          #                          {%- if states.sensor.cold_flu.state|float <= 2.4 %}
          #                          Low
          #                          {%- elif states.sensor.cold_flu.state|float <= 4.8 %}
          #                          Medium-Low
          #                          {%- elif states.sensor.cold_flu.state|float <= 7.2 %}
          #                          Medium
          #                          {%- elif states.sensor.cold_flu.state|float <= 9.6 %}
          #                          Medium-High
          #                          {%- elif states.sensor.cold_flu.state|float <= 12.0 %}
          #                          High
          #                          {% else %}
          #                          Unknown
          #                          {%- endif %}
        - platform: darksky
          api_key: !secret darksky_api
          monitored_conditions:
                  - cloud_cover
                  - daily_summary
                  - hourly_summary
                  - humidity
                  - nearest_storm_distance
                  - summary
                  - temperature
                  - temperature_max
                  - temperature_min
                  - wind_speed


automation:  
  - alias: Proactive Future Rain Notification
    trigger:
            platform: numeric_state
            entity_id: sensor.dark_sky_nearest_storm_distance
            below: 10
    action:
            service: notify.html5_nexus5
            data:
                    title: "Risque de pluie"
                    message: "il y a de l'orage a moins de 10 km d'ici!"
